// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://craciiivwgywladprgxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyYWNpaWl2d2d5d2xhZHByZ3h3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDE5MjIsImV4cCI6MjA2ODY3NzkyMn0.LWQqTq3TuKJ_5XcJuWplBs0MayIKfKWTw08onsICB6A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});